//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReferenceIIS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceIIS.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        ConsoleApplication1.ServiceReferenceIIS.GetDataResponse GetData(ConsoleApplication1.ServiceReferenceIIS.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.GetDataResponse> GetDataAsync(ConsoleApplication1.ServiceReferenceIIS.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ConsoleApplication1.ServiceReferenceIIS.GetDataUsingDataContractResponse GetDataUsingDataContract(ConsoleApplication1.ServiceReferenceIIS.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(ConsoleApplication1.ServiceReferenceIIS.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncCitiesKudaGo", ReplyAction="http://tempuri.org/IService1/SyncCitiesKudaGoResponse")]
        ConsoleApplication1.ServiceReferenceIIS.SyncCitiesKudaGoResponse SyncCitiesKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncCitiesKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncCitiesKudaGo", ReplyAction="http://tempuri.org/IService1/SyncCitiesKudaGoResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncCitiesKudaGoResponse> SyncCitiesKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncCitiesKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncCitiesCulture", ReplyAction="http://tempuri.org/IService1/SyncCitiesCultureResponse")]
        ConsoleApplication1.ServiceReferenceIIS.SyncCitiesCultureResponse SyncCitiesCulture(ConsoleApplication1.ServiceReferenceIIS.SyncCitiesCultureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncCitiesCulture", ReplyAction="http://tempuri.org/IService1/SyncCitiesCultureResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncCitiesCultureResponse> SyncCitiesCultureAsync(ConsoleApplication1.ServiceReferenceIIS.SyncCitiesCultureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncEventsKudaGo", ReplyAction="http://tempuri.org/IService1/SyncEventsKudaGoResponse")]
        ConsoleApplication1.ServiceReferenceIIS.SyncEventsKudaGoResponse SyncEventsKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncEventsKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncEventsKudaGo", ReplyAction="http://tempuri.org/IService1/SyncEventsKudaGoResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncEventsKudaGoResponse> SyncEventsKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncEventsKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncPlacesKudaGo", ReplyAction="http://tempuri.org/IService1/SyncPlacesKudaGoResponse")]
        ConsoleApplication1.ServiceReferenceIIS.SyncPlacesKudaGoResponse SyncPlacesKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncPlacesKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncPlacesKudaGo", ReplyAction="http://tempuri.org/IService1/SyncPlacesKudaGoResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncPlacesKudaGoResponse> SyncPlacesKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncPlacesKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncFilmsKudaGo", ReplyAction="http://tempuri.org/IService1/SyncFilmsKudaGoResponse")]
        ConsoleApplication1.ServiceReferenceIIS.SyncFilmsKudaGoResponse SyncFilmsKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncFilmsKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncFilmsKudaGo", ReplyAction="http://tempuri.org/IService1/SyncFilmsKudaGoResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncFilmsKudaGoResponse> SyncFilmsKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncFilmsKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncFilmDetailsKudaGo", ReplyAction="http://tempuri.org/IService1/SyncFilmDetailsKudaGoResponse")]
        ConsoleApplication1.ServiceReferenceIIS.SyncFilmDetailsKudaGoResponse SyncFilmDetailsKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncFilmDetailsKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncFilmDetailsKudaGo", ReplyAction="http://tempuri.org/IService1/SyncFilmDetailsKudaGoResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncFilmDetailsKudaGoResponse> SyncFilmDetailsKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncFilmDetailsKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncShowFilmsKudaGo", ReplyAction="http://tempuri.org/IService1/SyncShowFilmsKudaGoResponse")]
        ConsoleApplication1.ServiceReferenceIIS.SyncShowFilmsKudaGoResponse SyncShowFilmsKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncShowFilmsKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncShowFilmsKudaGo", ReplyAction="http://tempuri.org/IService1/SyncShowFilmsKudaGoResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncShowFilmsKudaGoResponse> SyncShowFilmsKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncShowFilmsKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncShowsKudaGo", ReplyAction="http://tempuri.org/IService1/SyncShowsKudaGoResponse")]
        ConsoleApplication1.ServiceReferenceIIS.SyncShowsKudaGoResponse SyncShowsKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncShowsKudaGoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncShowsKudaGo", ReplyAction="http://tempuri.org/IService1/SyncShowsKudaGoResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncShowsKudaGoResponse> SyncShowsKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncShowsKudaGoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(int value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDataResult;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReferenceIIS.CompositeType composite;
        
        public GetDataUsingDataContractRequest() {
        }
        
        public GetDataUsingDataContractRequest(ConsoleApplication1.ServiceReferenceIIS.CompositeType composite) {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication1.ServiceReferenceIIS.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse() {
        }
        
        public GetDataUsingDataContractResponse(ConsoleApplication1.ServiceReferenceIIS.CompositeType GetDataUsingDataContractResult) {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncCitiesKudaGo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncCitiesKudaGoRequest {
        
        public SyncCitiesKudaGoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncCitiesKudaGoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncCitiesKudaGoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SyncCitiesKudaGoResult;
        
        public SyncCitiesKudaGoResponse() {
        }
        
        public SyncCitiesKudaGoResponse(bool SyncCitiesKudaGoResult) {
            this.SyncCitiesKudaGoResult = SyncCitiesKudaGoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncCitiesCulture", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncCitiesCultureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string city;
        
        public SyncCitiesCultureRequest() {
        }
        
        public SyncCitiesCultureRequest(string city) {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncCitiesCultureResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncCitiesCultureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SyncCitiesCultureResult;
        
        public SyncCitiesCultureResponse() {
        }
        
        public SyncCitiesCultureResponse(bool SyncCitiesCultureResult) {
            this.SyncCitiesCultureResult = SyncCitiesCultureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncEventsKudaGo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncEventsKudaGoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime eventDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int locationId;
        
        public SyncEventsKudaGoRequest() {
        }
        
        public SyncEventsKudaGoRequest(System.DateTime eventDate, int locationId) {
            this.eventDate = eventDate;
            this.locationId = locationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncEventsKudaGoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncEventsKudaGoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SyncEventsKudaGoResult;
        
        public SyncEventsKudaGoResponse() {
        }
        
        public SyncEventsKudaGoResponse(bool SyncEventsKudaGoResult) {
            this.SyncEventsKudaGoResult = SyncEventsKudaGoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncPlacesKudaGo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncPlacesKudaGoRequest {
        
        public SyncPlacesKudaGoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncPlacesKudaGoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncPlacesKudaGoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SyncPlacesKudaGoResult;
        
        public SyncPlacesKudaGoResponse() {
        }
        
        public SyncPlacesKudaGoResponse(bool SyncPlacesKudaGoResult) {
            this.SyncPlacesKudaGoResult = SyncPlacesKudaGoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncFilmsKudaGo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncFilmsKudaGoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime dateTo;
        
        public SyncFilmsKudaGoRequest() {
        }
        
        public SyncFilmsKudaGoRequest(System.DateTime dateFrom, System.DateTime dateTo) {
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncFilmsKudaGoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncFilmsKudaGoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SyncFilmsKudaGoResult;
        
        public SyncFilmsKudaGoResponse() {
        }
        
        public SyncFilmsKudaGoResponse(bool SyncFilmsKudaGoResult) {
            this.SyncFilmsKudaGoResult = SyncFilmsKudaGoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncFilmDetailsKudaGo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncFilmDetailsKudaGoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Id;
        
        public SyncFilmDetailsKudaGoRequest() {
        }
        
        public SyncFilmDetailsKudaGoRequest(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncFilmDetailsKudaGoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncFilmDetailsKudaGoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SyncFilmDetailsKudaGoResult;
        
        public SyncFilmDetailsKudaGoResponse() {
        }
        
        public SyncFilmDetailsKudaGoResponse(bool SyncFilmDetailsKudaGoResult) {
            this.SyncFilmDetailsKudaGoResult = SyncFilmDetailsKudaGoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncShowFilmsKudaGo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncShowFilmsKudaGoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime dateTo;
        
        public SyncShowFilmsKudaGoRequest() {
        }
        
        public SyncShowFilmsKudaGoRequest(System.DateTime dateFrom, System.DateTime dateTo) {
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncShowFilmsKudaGoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncShowFilmsKudaGoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SyncShowFilmsKudaGoResult;
        
        public SyncShowFilmsKudaGoResponse() {
        }
        
        public SyncShowFilmsKudaGoResponse(bool SyncShowFilmsKudaGoResult) {
            this.SyncShowFilmsKudaGoResult = SyncShowFilmsKudaGoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncShowsKudaGo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncShowsKudaGoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.DateTime dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime dateTo;
        
        public SyncShowsKudaGoRequest() {
        }
        
        public SyncShowsKudaGoRequest(System.DateTime dateFrom, System.DateTime dateTo) {
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncShowsKudaGoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyncShowsKudaGoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SyncShowsKudaGoResult;
        
        public SyncShowsKudaGoResponse() {
        }
        
        public SyncShowsKudaGoResponse(bool SyncShowsKudaGoResult) {
            this.SyncShowsKudaGoResult = SyncShowsKudaGoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleApplication1.ServiceReferenceIIS.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReferenceIIS.IService1>, ConsoleApplication1.ServiceReferenceIIS.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1.ServiceReferenceIIS.GetDataResponse GetData(ConsoleApplication1.ServiceReferenceIIS.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.GetDataResponse> GetDataAsync(ConsoleApplication1.ServiceReferenceIIS.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public ConsoleApplication1.ServiceReferenceIIS.GetDataUsingDataContractResponse GetDataUsingDataContract(ConsoleApplication1.ServiceReferenceIIS.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContract(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(ConsoleApplication1.ServiceReferenceIIS.GetDataUsingDataContractRequest request) {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public ConsoleApplication1.ServiceReferenceIIS.SyncCitiesKudaGoResponse SyncCitiesKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncCitiesKudaGoRequest request) {
            return base.Channel.SyncCitiesKudaGo(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncCitiesKudaGoResponse> SyncCitiesKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncCitiesKudaGoRequest request) {
            return base.Channel.SyncCitiesKudaGoAsync(request);
        }
        
        public ConsoleApplication1.ServiceReferenceIIS.SyncCitiesCultureResponse SyncCitiesCulture(ConsoleApplication1.ServiceReferenceIIS.SyncCitiesCultureRequest request) {
            return base.Channel.SyncCitiesCulture(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncCitiesCultureResponse> SyncCitiesCultureAsync(ConsoleApplication1.ServiceReferenceIIS.SyncCitiesCultureRequest request) {
            return base.Channel.SyncCitiesCultureAsync(request);
        }
        
        public ConsoleApplication1.ServiceReferenceIIS.SyncEventsKudaGoResponse SyncEventsKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncEventsKudaGoRequest request) {
            return base.Channel.SyncEventsKudaGo(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncEventsKudaGoResponse> SyncEventsKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncEventsKudaGoRequest request) {
            return base.Channel.SyncEventsKudaGoAsync(request);
        }
        
        public ConsoleApplication1.ServiceReferenceIIS.SyncPlacesKudaGoResponse SyncPlacesKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncPlacesKudaGoRequest request) {
            return base.Channel.SyncPlacesKudaGo(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncPlacesKudaGoResponse> SyncPlacesKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncPlacesKudaGoRequest request) {
            return base.Channel.SyncPlacesKudaGoAsync(request);
        }
        
        public ConsoleApplication1.ServiceReferenceIIS.SyncFilmsKudaGoResponse SyncFilmsKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncFilmsKudaGoRequest request) {
            return base.Channel.SyncFilmsKudaGo(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncFilmsKudaGoResponse> SyncFilmsKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncFilmsKudaGoRequest request) {
            return base.Channel.SyncFilmsKudaGoAsync(request);
        }
        
        public ConsoleApplication1.ServiceReferenceIIS.SyncFilmDetailsKudaGoResponse SyncFilmDetailsKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncFilmDetailsKudaGoRequest request) {
            return base.Channel.SyncFilmDetailsKudaGo(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncFilmDetailsKudaGoResponse> SyncFilmDetailsKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncFilmDetailsKudaGoRequest request) {
            return base.Channel.SyncFilmDetailsKudaGoAsync(request);
        }
        
        public ConsoleApplication1.ServiceReferenceIIS.SyncShowFilmsKudaGoResponse SyncShowFilmsKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncShowFilmsKudaGoRequest request) {
            return base.Channel.SyncShowFilmsKudaGo(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncShowFilmsKudaGoResponse> SyncShowFilmsKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncShowFilmsKudaGoRequest request) {
            return base.Channel.SyncShowFilmsKudaGoAsync(request);
        }
        
        public ConsoleApplication1.ServiceReferenceIIS.SyncShowsKudaGoResponse SyncShowsKudaGo(ConsoleApplication1.ServiceReferenceIIS.SyncShowsKudaGoRequest request) {
            return base.Channel.SyncShowsKudaGo(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReferenceIIS.SyncShowsKudaGoResponse> SyncShowsKudaGoAsync(ConsoleApplication1.ServiceReferenceIIS.SyncShowsKudaGoRequest request) {
            return base.Channel.SyncShowsKudaGoAsync(request);
        }
    }
}
