//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleApplication1.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncCitiesKudaGoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncCitiesCultureOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncEventsKudaGoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncPlacesKudaGoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncFilmsKudaGoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncFilmDetailsKudaGoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncShowFilmsKudaGoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncShowsKudaGoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::ConsoleApplication1.Properties.Settings.Default.ConsoleApplication1_WebReference_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        public event SyncCitiesKudaGoCompletedEventHandler SyncCitiesKudaGoCompleted;
        
        /// <remarks/>
        public event SyncCitiesCultureCompletedEventHandler SyncCitiesCultureCompleted;
        
        /// <remarks/>
        public event SyncEventsKudaGoCompletedEventHandler SyncEventsKudaGoCompleted;
        
        /// <remarks/>
        public event SyncPlacesKudaGoCompletedEventHandler SyncPlacesKudaGoCompleted;
        
        /// <remarks/>
        public event SyncFilmsKudaGoCompletedEventHandler SyncFilmsKudaGoCompleted;
        
        /// <remarks/>
        public event SyncFilmDetailsKudaGoCompletedEventHandler SyncFilmDetailsKudaGoCompleted;
        
        /// <remarks/>
        public event SyncShowFilmsKudaGoCompletedEventHandler SyncShowFilmsKudaGoCompleted;
        
        /// <remarks/>
        public event SyncShowsKudaGoCompletedEventHandler SyncShowsKudaGoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SyncCitiesKudaGo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncCitiesKudaGo(out bool SyncCitiesKudaGoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SyncCitiesKudaGoResultSpecified) {
            object[] results = this.Invoke("SyncCitiesKudaGo", new object[0]);
            SyncCitiesKudaGoResult = ((bool)(results[0]));
            SyncCitiesKudaGoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SyncCitiesKudaGoAsync() {
            this.SyncCitiesKudaGoAsync(null);
        }
        
        /// <remarks/>
        public void SyncCitiesKudaGoAsync(object userState) {
            if ((this.SyncCitiesKudaGoOperationCompleted == null)) {
                this.SyncCitiesKudaGoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncCitiesKudaGoOperationCompleted);
            }
            this.InvokeAsync("SyncCitiesKudaGo", new object[0], this.SyncCitiesKudaGoOperationCompleted, userState);
        }
        
        private void OnSyncCitiesKudaGoOperationCompleted(object arg) {
            if ((this.SyncCitiesKudaGoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncCitiesKudaGoCompleted(this, new SyncCitiesKudaGoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SyncCitiesCulture", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncCitiesCulture([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string city, out bool SyncCitiesCultureResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SyncCitiesCultureResultSpecified) {
            object[] results = this.Invoke("SyncCitiesCulture", new object[] {
                        city});
            SyncCitiesCultureResult = ((bool)(results[0]));
            SyncCitiesCultureResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SyncCitiesCultureAsync(string city) {
            this.SyncCitiesCultureAsync(city, null);
        }
        
        /// <remarks/>
        public void SyncCitiesCultureAsync(string city, object userState) {
            if ((this.SyncCitiesCultureOperationCompleted == null)) {
                this.SyncCitiesCultureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncCitiesCultureOperationCompleted);
            }
            this.InvokeAsync("SyncCitiesCulture", new object[] {
                        city}, this.SyncCitiesCultureOperationCompleted, userState);
        }
        
        private void OnSyncCitiesCultureOperationCompleted(object arg) {
            if ((this.SyncCitiesCultureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncCitiesCultureCompleted(this, new SyncCitiesCultureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SyncEventsKudaGo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncEventsKudaGo(System.DateTime eventDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool eventDateSpecified, int locationId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool locationIdSpecified, out bool SyncEventsKudaGoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SyncEventsKudaGoResultSpecified) {
            object[] results = this.Invoke("SyncEventsKudaGo", new object[] {
                        eventDate,
                        eventDateSpecified,
                        locationId,
                        locationIdSpecified});
            SyncEventsKudaGoResult = ((bool)(results[0]));
            SyncEventsKudaGoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SyncEventsKudaGoAsync(System.DateTime eventDate, bool eventDateSpecified, int locationId, bool locationIdSpecified) {
            this.SyncEventsKudaGoAsync(eventDate, eventDateSpecified, locationId, locationIdSpecified, null);
        }
        
        /// <remarks/>
        public void SyncEventsKudaGoAsync(System.DateTime eventDate, bool eventDateSpecified, int locationId, bool locationIdSpecified, object userState) {
            if ((this.SyncEventsKudaGoOperationCompleted == null)) {
                this.SyncEventsKudaGoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncEventsKudaGoOperationCompleted);
            }
            this.InvokeAsync("SyncEventsKudaGo", new object[] {
                        eventDate,
                        eventDateSpecified,
                        locationId,
                        locationIdSpecified}, this.SyncEventsKudaGoOperationCompleted, userState);
        }
        
        private void OnSyncEventsKudaGoOperationCompleted(object arg) {
            if ((this.SyncEventsKudaGoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncEventsKudaGoCompleted(this, new SyncEventsKudaGoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SyncPlacesKudaGo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncPlacesKudaGo(out bool SyncPlacesKudaGoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SyncPlacesKudaGoResultSpecified) {
            object[] results = this.Invoke("SyncPlacesKudaGo", new object[0]);
            SyncPlacesKudaGoResult = ((bool)(results[0]));
            SyncPlacesKudaGoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SyncPlacesKudaGoAsync() {
            this.SyncPlacesKudaGoAsync(null);
        }
        
        /// <remarks/>
        public void SyncPlacesKudaGoAsync(object userState) {
            if ((this.SyncPlacesKudaGoOperationCompleted == null)) {
                this.SyncPlacesKudaGoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncPlacesKudaGoOperationCompleted);
            }
            this.InvokeAsync("SyncPlacesKudaGo", new object[0], this.SyncPlacesKudaGoOperationCompleted, userState);
        }
        
        private void OnSyncPlacesKudaGoOperationCompleted(object arg) {
            if ((this.SyncPlacesKudaGoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncPlacesKudaGoCompleted(this, new SyncPlacesKudaGoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SyncFilmsKudaGo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncFilmsKudaGo(System.DateTime dateFrom, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateFromSpecified, System.DateTime dateTo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateToSpecified, out bool SyncFilmsKudaGoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SyncFilmsKudaGoResultSpecified) {
            object[] results = this.Invoke("SyncFilmsKudaGo", new object[] {
                        dateFrom,
                        dateFromSpecified,
                        dateTo,
                        dateToSpecified});
            SyncFilmsKudaGoResult = ((bool)(results[0]));
            SyncFilmsKudaGoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SyncFilmsKudaGoAsync(System.DateTime dateFrom, bool dateFromSpecified, System.DateTime dateTo, bool dateToSpecified) {
            this.SyncFilmsKudaGoAsync(dateFrom, dateFromSpecified, dateTo, dateToSpecified, null);
        }
        
        /// <remarks/>
        public void SyncFilmsKudaGoAsync(System.DateTime dateFrom, bool dateFromSpecified, System.DateTime dateTo, bool dateToSpecified, object userState) {
            if ((this.SyncFilmsKudaGoOperationCompleted == null)) {
                this.SyncFilmsKudaGoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncFilmsKudaGoOperationCompleted);
            }
            this.InvokeAsync("SyncFilmsKudaGo", new object[] {
                        dateFrom,
                        dateFromSpecified,
                        dateTo,
                        dateToSpecified}, this.SyncFilmsKudaGoOperationCompleted, userState);
        }
        
        private void OnSyncFilmsKudaGoOperationCompleted(object arg) {
            if ((this.SyncFilmsKudaGoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncFilmsKudaGoCompleted(this, new SyncFilmsKudaGoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SyncFilmDetailsKudaGo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncFilmDetailsKudaGo(int Id, [System.Xml.Serialization.XmlIgnoreAttribute()] bool IdSpecified, out bool SyncFilmDetailsKudaGoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SyncFilmDetailsKudaGoResultSpecified) {
            object[] results = this.Invoke("SyncFilmDetailsKudaGo", new object[] {
                        Id,
                        IdSpecified});
            SyncFilmDetailsKudaGoResult = ((bool)(results[0]));
            SyncFilmDetailsKudaGoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SyncFilmDetailsKudaGoAsync(int Id, bool IdSpecified) {
            this.SyncFilmDetailsKudaGoAsync(Id, IdSpecified, null);
        }
        
        /// <remarks/>
        public void SyncFilmDetailsKudaGoAsync(int Id, bool IdSpecified, object userState) {
            if ((this.SyncFilmDetailsKudaGoOperationCompleted == null)) {
                this.SyncFilmDetailsKudaGoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncFilmDetailsKudaGoOperationCompleted);
            }
            this.InvokeAsync("SyncFilmDetailsKudaGo", new object[] {
                        Id,
                        IdSpecified}, this.SyncFilmDetailsKudaGoOperationCompleted, userState);
        }
        
        private void OnSyncFilmDetailsKudaGoOperationCompleted(object arg) {
            if ((this.SyncFilmDetailsKudaGoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncFilmDetailsKudaGoCompleted(this, new SyncFilmDetailsKudaGoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SyncShowFilmsKudaGo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncShowFilmsKudaGo(System.DateTime dateFrom, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateFromSpecified, System.DateTime dateTo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateToSpecified, out bool SyncShowFilmsKudaGoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SyncShowFilmsKudaGoResultSpecified) {
            object[] results = this.Invoke("SyncShowFilmsKudaGo", new object[] {
                        dateFrom,
                        dateFromSpecified,
                        dateTo,
                        dateToSpecified});
            SyncShowFilmsKudaGoResult = ((bool)(results[0]));
            SyncShowFilmsKudaGoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SyncShowFilmsKudaGoAsync(System.DateTime dateFrom, bool dateFromSpecified, System.DateTime dateTo, bool dateToSpecified) {
            this.SyncShowFilmsKudaGoAsync(dateFrom, dateFromSpecified, dateTo, dateToSpecified, null);
        }
        
        /// <remarks/>
        public void SyncShowFilmsKudaGoAsync(System.DateTime dateFrom, bool dateFromSpecified, System.DateTime dateTo, bool dateToSpecified, object userState) {
            if ((this.SyncShowFilmsKudaGoOperationCompleted == null)) {
                this.SyncShowFilmsKudaGoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncShowFilmsKudaGoOperationCompleted);
            }
            this.InvokeAsync("SyncShowFilmsKudaGo", new object[] {
                        dateFrom,
                        dateFromSpecified,
                        dateTo,
                        dateToSpecified}, this.SyncShowFilmsKudaGoOperationCompleted, userState);
        }
        
        private void OnSyncShowFilmsKudaGoOperationCompleted(object arg) {
            if ((this.SyncShowFilmsKudaGoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncShowFilmsKudaGoCompleted(this, new SyncShowFilmsKudaGoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SyncShowsKudaGo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SyncShowsKudaGo(System.DateTime dateFrom, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateFromSpecified, System.DateTime dateTo, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateToSpecified, out bool SyncShowsKudaGoResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool SyncShowsKudaGoResultSpecified) {
            object[] results = this.Invoke("SyncShowsKudaGo", new object[] {
                        dateFrom,
                        dateFromSpecified,
                        dateTo,
                        dateToSpecified});
            SyncShowsKudaGoResult = ((bool)(results[0]));
            SyncShowsKudaGoResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void SyncShowsKudaGoAsync(System.DateTime dateFrom, bool dateFromSpecified, System.DateTime dateTo, bool dateToSpecified) {
            this.SyncShowsKudaGoAsync(dateFrom, dateFromSpecified, dateTo, dateToSpecified, null);
        }
        
        /// <remarks/>
        public void SyncShowsKudaGoAsync(System.DateTime dateFrom, bool dateFromSpecified, System.DateTime dateTo, bool dateToSpecified, object userState) {
            if ((this.SyncShowsKudaGoOperationCompleted == null)) {
                this.SyncShowsKudaGoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncShowsKudaGoOperationCompleted);
            }
            this.InvokeAsync("SyncShowsKudaGo", new object[] {
                        dateFrom,
                        dateFromSpecified,
                        dateTo,
                        dateToSpecified}, this.SyncShowsKudaGoOperationCompleted, userState);
        }
        
        private void OnSyncShowsKudaGoOperationCompleted(object arg) {
            if ((this.SyncShowsKudaGoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncShowsKudaGoCompleted(this, new SyncShowsKudaGoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SyncCitiesKudaGoCompletedEventHandler(object sender, SyncCitiesKudaGoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncCitiesKudaGoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncCitiesKudaGoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool SyncCitiesKudaGoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SyncCitiesKudaGoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SyncCitiesCultureCompletedEventHandler(object sender, SyncCitiesCultureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncCitiesCultureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncCitiesCultureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool SyncCitiesCultureResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SyncCitiesCultureResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SyncEventsKudaGoCompletedEventHandler(object sender, SyncEventsKudaGoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncEventsKudaGoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncEventsKudaGoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool SyncEventsKudaGoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SyncEventsKudaGoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SyncPlacesKudaGoCompletedEventHandler(object sender, SyncPlacesKudaGoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncPlacesKudaGoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncPlacesKudaGoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool SyncPlacesKudaGoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SyncPlacesKudaGoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SyncFilmsKudaGoCompletedEventHandler(object sender, SyncFilmsKudaGoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncFilmsKudaGoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncFilmsKudaGoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool SyncFilmsKudaGoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SyncFilmsKudaGoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SyncFilmDetailsKudaGoCompletedEventHandler(object sender, SyncFilmDetailsKudaGoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncFilmDetailsKudaGoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncFilmDetailsKudaGoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool SyncFilmDetailsKudaGoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SyncFilmDetailsKudaGoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SyncShowFilmsKudaGoCompletedEventHandler(object sender, SyncShowFilmsKudaGoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncShowFilmsKudaGoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncShowFilmsKudaGoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool SyncShowFilmsKudaGoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SyncShowFilmsKudaGoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SyncShowsKudaGoCompletedEventHandler(object sender, SyncShowsKudaGoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncShowsKudaGoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncShowsKudaGoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool SyncShowsKudaGoResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool SyncShowsKudaGoResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591